---
# This role installs httpd

- name: "Install php"
  yum:
    name: '{{ item }}'
    state: present
  with_items:
   - mod_php71w
   - php71w-opcache
   - php71w-common

- name: "create vhosts"
  file:
    state: directory
    path: "{{item.documentroot}}"
    mode: 0755
  with_items:
    - "{{ apache_vhosts }}"

- name: "install index file"
  template:
    src: "index.html.j2"
    dest: "{{item.documentroot}}/index.html"
  with_items:
    - "{{ apache_vhosts }}"

- name: "get php tester"
  git:
    repo: 'https://github.com/cbrandel/php-tester'
    dest: /tmp/php-tester

- name: "install php tester"
  synchronize:
    src: /tmp/php-tester/public/
    dest: "{{item.documentroot}}/{{item.php_context|default('')}}"
  with_items:
    - "{{ apache_vhosts }}"
  delegate_to: "{{ansible_hostname}}"

- name: "install and configure apache"
  include_role:
    name: geerlingguy.apache

- name: "add our unusual port setting"
  lineinfile:
    path: '/etc/httpd/conf/httpd.conf'
    regexp: '^Listen {{ web_httpd_port }}'
    line: 'Listen {{ web_httpd_port }} http'

- name: "remove ssl config"
  file:
    state: absent
    path: "/etc/httpd/conf.d/ssl.conf"

- name: "open httpd log directory"
  file:
    state: directory
    path: "/var/log/httpd"
    recurse: false
    mode: "g+rx,o+rx"

- meta: flush_handlers

- name: http service state
  service: name=httpd state=started enabled=yes
