---
# This role installs httpd

- name: Install httpD
  yum:
    name: '{{ item }}'
    state: present
  with_items:
   - httpd
   - php71w-fpm
   - php71w-opcache
   - php71w-common

- name: http service state
  service: name=httpd state=started enabled=yes
